version: v2

global:
  runner:
    os_image: ubuntu

tasks:
  say-hello:
    steps:
      -  name: print Hello world
      -  run: echo "Hello world from RazorOps!"

      -  name: show Directory structure
      -  run: ls -la

      -  name: Show System Info
      -  run : uname -a
