version: v2

global:
  runner:
    os_image: ubuntu  # Use a Linux VM environment

tasks:
  say-hello:  # Name of the task
    steps:
      - name: Print Hello World
        run: echo "Hello World from RazorOps!"
      - name: Show Directory Structure
        run: ls -la
      - name: Show System Info
        run: uname -a
