version: v2

global:
  runner:
    os_image: ubuntu  # Use a Linux VM environment

tasks:
  say-hello:  # Name of the task
    steps:
      - step_type: run
        name: print-hello-world
        run: echo "Hello World from RazorOps!"
      - step_type: run
        name: show-directory-structure
        run: ls -la
      - step_type: run
        name: show-system-info
        run: uname -a
