version: v2

global:
  runner:
    os_image: ubuntu  # Use a Linux VM environment

tasks:
  say-hello:  # Name of the task
    steps:
    - checkout
    - run: echo "Hello World from RazorOps!"
    - run: ls -la
    - run: uname -a
